Added page and functions for editing
archlich03/spotify-link-to-json pull request #8
Opened 2023-09-19 13:20 UTC by nitrogency

Added the following:

- New page called `edit.php` meant for... editing. Found data (by ID) is shown in the input fields, where it can be changed. 
- Added two functions to `functions.php` which cut down code reuse.

2023-09-19 14:21 UTC, archlich03 requested changes

2023-09-19 14:21 UTC, archlich03 commented on edit.php
> +            $data["data"][$key]["url"] = $_POST["url"];
I think this is missing escaping

2023-09-19 14:21 UTC, archlich03 commented on edit.php
> +            <p>Check frequency (in hours): <input type="number" name="frequency" min="-1" value="<?php echo htmlspecialchars($frequency); ?>"></p>
Don't know what's exactly causing it, but the backend processing doesn't allow me to set -1 as the frequency

2023-09-19 14:21 UTC, archlich03 commented on edit.php
> +    elseif ($_SERVER["REQUEST_METHOD"] == "GET" && isset($_GET["id"])) {
I think it would be wise to implement another else condition to `die()` the page, because this page should always be accessed with at least the GET parameter (if there's no GET, there's nothing for the page to do)

2023-09-19 14:21 UTC, archlich03 commented on edit.php
> +            $data["data"][$key]["frequency"] = (int)$_POST["frequency"];
i think it should be wise to implement the same checks you did with the HTML form. If you do inspect element on them and change the limits on the client side, there wouldn't be any backend protections against it

2023-09-19 14:51 UTC, archlich03 requested changes

2023-09-19 14:51 UTC, archlich03 commented on edit.php
> +        }
Error handling would be nice

2023-09-19 14:51 UTC, archlich03 commented on edit.php
> +        $id = (int)$_GET["id"];
Input sanitation needed

2023-09-19 14:51 UTC, archlich03 commented on edit.php
> +        }
Error handling needed

2023-09-19 15:04 UTC, archlich03 commented on edit.php
> +            $data["data"][$key]["url"] = $_POST["url"];
also, maybe worth implementing a regex check for the URL to see if the standard is being followed? (in case it gets manipulated clientside)

2023-09-20 12:27 UTC, nitrogency commented on edit.php
> +            $data["data"][$key]["url"] = $_POST["url"];
the URL is checked for errors in the IF statement that this part of the code is in. Referring to `if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST["id"]) **&& empty($urlErr)** && empty($frequencyErr)) {`
unless you're referring to something else?

2023-09-20 12:30 UTC, nitrogency commented on edit.php
> +            <p>Check frequency (in hours): <input type="number" name="frequency" min="-1" value="<?php echo htmlspecialchars($frequency); ?>"></p>
Fixed in commit.

2023-09-20 12:37 UTC, nitrogency commented on edit.php
> +    elseif ($_SERVER["REQUEST_METHOD"] == "GET" && isset($_GET["id"])) {
Fixed in [commit](https://github.com/archlich03/spotify-link-to-json/pull/8/commits/0293ada12f8107013fda47361b00514d14f2df09).

2023-09-20 13:02 UTC, archlich03 commented on edit.php
> +            $data["data"][$key]["url"] = $_POST["url"];
My bad, didn't put 2 and 2 together, this is checked in `validate.php` :)

2023-09-20 13:35 UTC, nitrogency commented on edit.php
> +        }
Fixed in [commit](https://github.com/archlich03/spotify-link-to-json/pull/8/commits/97c576e042eb18043b618c8e25d5820d227eb22e).

2023-09-20 13:35 UTC, nitrogency commented on edit.php
> +        $id = (int)$_GET["id"];
Fixed in [commit](https://github.com/archlich03/spotify-link-to-json/pull/8/commits/97c576e042eb18043b618c8e25d5820d227eb22e).

2023-09-20 13:36 UTC, nitrogency commented on edit.php
> +        }
Fixed in [commit](https://github.com/archlich03/spotify-link-to-json/pull/8/commits/97c576e042eb18043b618c8e25d5820d227eb22e).

2023-09-20 16:59 UTC, archlich03 approved these changes
Everything seems good now. Good job!

2023-09-20 17:00 UTC, merged